version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    hostname: db
    user: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./dbdata/:/var/lib/mysql:rw
      - ./docker-data:/docker-entrypoint-initdb.d
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    build: ./docker-nginx/
    container_name: wordpress
    ports:
      - 8080:80
    extra_hosts:
      - "portfolio.local:127.0.0.1"
    volumes:
      - ./wordpress/:/var/www/html/
    networks:
      - app-network

  php:
    build: ./docker-php/
    container_name: php
    expose:
      - 9000
    extra_hosts:
      - "portfolio.local:127.0.0.1"
    volumes:
      - ./wordpress/:/var/www/html/
    networks:
      - app-network
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./redis/data:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=asdf1234qweras678678dfzxcv
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
