version: "3.9"

services:
    wordpress:
      build: ./docker-nginx/
      container_name: wordpress
      ports:
       - 8080:80
      volumes:
        - ./wordpress/:/var/www/html/

    php:
      build: ./docker-php/
      expose:
        - 9000
      volumes:
        - ./wordpress/:/var/www/html/
